In [2]:
import numpy as np

# Array a partir de uma lista

In [7]:
qtd = [2,5,10,20,35]
custo = [100,150,450,320,195]

#array é diferente de lista

In [8]:
arr1 = numpy.array(qtd)

In [9]:
arr2 = numpy.array(custo)

In [11]:
estoque = qtd*custo

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
estoque = arr1*arr2

In [13]:
estoque

array([ 200,  750, 4500, 6400, 6825])

In [14]:
custo = [100,150,450,320,195]
venda = [123,234,563,643,213]

In [15]:
arr3 = np.array(custo)

In [16]:
arr4 = np.array(venda)

In [17]:
lucro = arr4 - arr3

In [18]:
lucro

array([ 23,  84, 113, 323,  18])

## Arrays a partir do numpy

## arange()

In [24]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(10,101,2,dtype=float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

## linspace

In [27]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [28]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## random - rand, randn, randint

In [30]:
np.random.rand(10)

array([0.70651525, 0.56389371, 0.24625839, 0.88761638, 0.396379  ,
       0.82261863, 0.96679163, 0.18678446, 0.63183388, 0.50721289])

In [31]:
np.random.randn(10)

array([ 0.36707305, -2.17455616,  0.32140748,  1.88921624,  0.1693971 ,
        0.36776937,  0.25309907,  0.7903123 ,  0.57056146, -1.07665958])

In [34]:
arr = np.random.randint(10,100,30)

In [35]:
len(arr)

30

## Array unidimensional

In [36]:
arr 

array([82, 41, 62, 74, 25, 97, 78, 42, 30, 30, 71, 42, 43, 35, 30, 38, 72,
       23, 29, 30, 54, 48, 50, 81, 72, 11, 48, 57, 87, 47])

## Array bidimensional

In [39]:
np.zeros((5,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Criando array unidimensional

In [44]:
arr = np.arange(1,11,dtype=int)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexação de arrays unidimensionais

In [47]:
arr[4]

5

In [48]:
arr[2:5]

array([3, 4, 5])

In [49]:
arr[:5]

array([1, 2, 3, 4, 5])

In [50]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexação de arrays bidimensionais

In [53]:
arr2 = np.random.randint(10,50,size=(3,3))

In [54]:
arr2

array([[13, 45, 34],
       [17, 11, 39],
       [22, 18, 36]])

In [55]:
arr2[1][1]

11

In [56]:
arr2[1][2]

39

In [ ]:
# arr2[linha][coluna]

In [59]:
arr2[2][0:2]

array([22, 18])

In [60]:
arr2[2,2]

36

In [61]:
arr2[1:,1:]

array([[11, 39],
       [18, 36]])

In [62]:
#lin = 1 2
#col = 2

In [64]:
arr2[1:3, 2:3]

array([[39],
       [36]])

In [65]:
arr2

array([[13, 45, 34],
       [17, 11, 39],
       [22, 18, 36]])

In [68]:
arr2[[2,0]]

array([[22, 18, 36],
       [13, 45, 34]])

## Selecionando Arrays

In [3]:
cadastro = np.random.randint(15,51,size=(50,10))

In [4]:
cadastro

array([[20, 41, 19, 47, 27, 21, 34, 18, 26, 30],
       [45, 21, 18, 34, 17, 35, 39, 45, 47, 15],
       [42, 23, 15, 22, 27, 21, 48, 37, 22, 29],
       [28, 21, 15, 23, 33, 27, 35, 21, 46, 38],
       [40, 33, 23, 30, 46, 45, 34, 16, 16, 23],
       [33, 25, 44, 35, 38, 39, 20, 22, 26, 20],
       [23, 34, 36, 16, 21, 32, 45, 37, 42, 40],
       [17, 50, 39, 33, 42, 23, 50, 17, 29, 30],
       [36, 19, 50, 41, 37, 34, 44, 29, 35, 48],
       [28, 30, 17, 43, 26, 30, 43, 26, 50, 45],
       [34, 46, 35, 39, 50, 18, 34, 47, 27, 27],
       [31, 18, 32, 32, 27, 43, 50, 33, 47, 46],
       [32, 31, 18, 32, 38, 44, 32, 29, 27, 40],
       [50, 46, 42, 16, 16, 48, 40, 36, 36, 39],
       [36, 47, 29, 28, 24, 25, 21, 17, 19, 39],
       [43, 49, 49, 17, 17, 24, 40, 49, 47, 37],
       [19, 46, 34, 25, 35, 36, 39, 23, 36, 37],
       [45, 45, 27, 20, 40, 26, 18, 33, 26, 43],
       [20, 42, 45, 15, 37, 16, 29, 36, 21, 37],
       [33, 35, 50, 31, 30, 33, 23, 31, 32, 35],
       [21, 21, 38, 

In [5]:
cadastro_maior18 = cadastro >18

In [6]:
cadastro_maior18

array([[ True,  True,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True,  True, False,  True, False,  True,  True,  True,  True,
        False],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True, 

In [12]:
cadastro[cadastro_maior18]

array([20, 41, 19, 47, 27, 21, 34, 26, 30, 45, 21, 34, 35, 39, 45, 47, 42,
       23, 22, 27, 21, 48, 37, 22, 29, 28, 21, 23, 33, 27, 35, 21, 46, 38,
       40, 33, 23, 30, 46, 45, 34, 23, 33, 25, 44, 35, 38, 39, 20, 22, 26,
       20, 23, 34, 36, 21, 32, 45, 37, 42, 40, 50, 39, 33, 42, 23, 50, 29,
       30, 36, 19, 50, 41, 37, 34, 44, 29, 35, 48, 28, 30, 43, 26, 30, 43,
       26, 50, 45, 34, 46, 35, 39, 50, 34, 47, 27, 27, 31, 32, 32, 27, 43,
       50, 33, 47, 46, 32, 31, 32, 38, 44, 32, 29, 27, 40, 50, 46, 42, 48,
       40, 36, 36, 39, 36, 47, 29, 28, 24, 25, 21, 19, 39, 43, 49, 49, 24,
       40, 49, 47, 37, 19, 46, 34, 25, 35, 36, 39, 23, 36, 37, 45, 45, 27,
       20, 40, 26, 33, 26, 43, 20, 42, 45, 37, 29, 36, 21, 37, 33, 35, 50,
       31, 30, 33, 23, 31, 32, 35, 21, 21, 38, 44, 25, 37, 33, 46, 27, 32,
       37, 19, 38, 32, 30, 21, 22, 20, 22, 44, 30, 32, 27, 25, 49, 24, 30,
       37, 21, 24, 45, 43, 32, 49, 34, 19, 45, 37, 36, 43, 41, 22, 49, 41,
       34, 42, 39, 49, 20

In [13]:
arr3 = cadastro[cadastro_maior18]

In [14]:
len(arr3)

442

In [15]:
cadastro_maior18.sum()

442

In [16]:
cadastro[2]

array([42, 23, 15, 22, 27, 21, 48, 37, 22, 29])

In [17]:
arr4 = cadastro[cadastro>25]

In [18]:
len(arr4)

345

In [19]:
condicao = (cadastro>20)

In [20]:
extraido = np.extract(condicao, cadastro)

In [21]:
extraido

array([41, 47, 27, 21, 34, 26, 30, 45, 21, 34, 35, 39, 45, 47, 42, 23, 22,
       27, 21, 48, 37, 22, 29, 28, 21, 23, 33, 27, 35, 21, 46, 38, 40, 33,
       23, 30, 46, 45, 34, 23, 33, 25, 44, 35, 38, 39, 22, 26, 23, 34, 36,
       21, 32, 45, 37, 42, 40, 50, 39, 33, 42, 23, 50, 29, 30, 36, 50, 41,
       37, 34, 44, 29, 35, 48, 28, 30, 43, 26, 30, 43, 26, 50, 45, 34, 46,
       35, 39, 50, 34, 47, 27, 27, 31, 32, 32, 27, 43, 50, 33, 47, 46, 32,
       31, 32, 38, 44, 32, 29, 27, 40, 50, 46, 42, 48, 40, 36, 36, 39, 36,
       47, 29, 28, 24, 25, 21, 39, 43, 49, 49, 24, 40, 49, 47, 37, 46, 34,
       25, 35, 36, 39, 23, 36, 37, 45, 45, 27, 40, 26, 33, 26, 43, 42, 45,
       37, 29, 36, 21, 37, 33, 35, 50, 31, 30, 33, 23, 31, 32, 35, 21, 21,
       38, 44, 25, 37, 33, 46, 27, 32, 37, 38, 32, 30, 21, 22, 22, 44, 30,
       32, 27, 25, 49, 24, 30, 37, 21, 24, 45, 43, 32, 49, 34, 45, 37, 36,
       43, 41, 22, 49, 41, 34, 42, 39, 49, 29, 43, 35, 33, 37, 39, 39, 44,
       24, 36, 27, 43, 36